### ISSUE TITLE
Xwayland tests not working if any X server exists already

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir-test-tools#60]
`latest/edge` seems to be… inconsistent. #59 should help a bit with discovery.
- @AlanGriffiths on 22.04 reports `--devmode` helps
- @Saviq on 22.10 reports `--devmode` does makes it pass, but black screen
- The lab is happy on 20.04 and 22.04 without `--devmode`

**Comment by AlanGriffiths** [comment]
A problem is that we fail when we try to use sockets that are already in use on the system.

Because snapd hides the real `/tmp/.X11-unix` we can't tell what sockets are actually available. So we're trying to use :0 and failing because it is already used by the host system. (IIRC We used to create some dummy sockets as a workaround. But I don't see that code anymore)

**Comment by Saviq** [comment]
OK, confirmed, and stopping any X thing on my machine made things work. Will split the `22/edge` issue then.

**Comment by AlanGriffiths** [comment]
> But I don't see that code anymore

That's because I deleted it: 9843500ab34046dde6c39fe8d763fc83982b1a45

**Comment by Saviq** [comment]
Fixed by #62
